export enum TypePromptEnum {
  LANCAMENTO_NOTAS = "LN",
  MARCACAO_PROVAS = "MP",
  CRIACAO_HORARIO = "CH",
}

export enum TypeAvaliation {
  PRIMEIRA_FREQUENCIA = "1F",
  SEGUNDA_FREQUENCIA = "2F",
  PRATICA = "P",
  NOTA_AVALIACAO_CONTINUA = "NA",
  EXAME = "E",
  RECURSO = "R",
  PROVA_ORAL = "O",
  EPOCA_ESPECIAL = "EE",
  NOTA_FINAL_CALCULADA = "NFC",
  NOTA_FINAL_LANCADA = "NFL",
  LANCAR_PRIMEIRA_FREQUENCIA = "L.1F",
  PROVA_ORAL_RECURSO = "OR",
  MELHORIA_NOTAS = "MN",
  SEGUNDA_FREQUENCIA_EXAME = "2FE",
}
