export interface MESTEMP {
  designacao: string;
  isencao: number;
  ordem_mes: number;
  ano_lectivo: number;
  prestacao: number;
  activo: number;
  activo_posgraduacao: number;
  data_limite: string;
  data_inicial: string;
  data_final: string;
  data_final_desconto: string | null;
  semestre: number;
  semestre_posgraduacao: number;
}
const mesTempConfig = [
  {
    designacao: 'OUT-',
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 23,
    prestacao: 1,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '10/15/2025',
    data_inicial: '10/1/2025',
    data_final: '10/31/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'NOV-',
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 23,
    prestacao: 2,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '11/17/2025',
    data_inicial: '11/1/2025',
    data_final: '11/30/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'DEZ-',
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 23,
    prestacao: 3,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '12/15/2025',
    data_inicial: '12/1/2025',
    data_final: '12/31/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'JAN-',
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 23,
    prestacao: 4,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '1/15/2026',
    data_inicial: '1/1/2026',
    data_final: '1/31/2026',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'FEV-',
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 23,
    prestacao: 5,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '2/16/2026',
    data_inicial: '2/1/2026',
    data_final: '2/28/2026',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'MAR-',
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 23,
    prestacao: 6,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '3/16/2026',
    data_inicial: '3/1/2026',
    data_final: '3/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'ABR-',
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 23,
    prestacao: 7,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '4/15/2026',
    data_inicial: '4/1/2026',
    data_final: '4/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'MAI-',
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 23,
    prestacao: 8,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '5/15/2026',
    data_inicial: '5/1/2026',
    data_final: '5/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'JUN-',
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 23,
    prestacao: 9,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '6/15/2026',
    data_inicial: '6/1/2026',
    data_final: '6/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'JUL-',
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 23,
    prestacao: 10,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '7/15/2026',
    data_inicial: '7/1/2026',
    data_final: '7/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'AGO-',
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 23,
    prestacao: 11,
    activo: 0,
    activo_posgraduacao: 0,
    data_limite: '8/17/2026',
    data_inicial: '8/1/2026',
    data_final: '8/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'SET-',
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 23,
    prestacao: 12,
    activo: 0,
    activo_posgraduacao: 0,
    data_limite: '9/15/2026',
    data_inicial: '9/1/2026',
    data_final: '9/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
];

export { mesTempConfig };
