export interface MESTEMP {
  designacao: string;
  isencao: number;
  ordem_mes: number;
  ano_lectivo: number;
  prestacao: number;
  activo: number;
  activo_posgraduacao: number;
  data_limite: string | null;
  data_inicial: string | null;
  data_final: string | null;
  data_final_desconto: string | null;
  semestre: number;
  semestre_posgraduacao: number;
}
const mesTempConfig: MESTEMP[] = [
  {
    designacao: 'OUT-',
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 23,
    prestacao: 1,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '10/15/2025',
    data_inicial: '10/1/2025',
    data_final: '10/31/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'NOV-',
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 23,
    prestacao: 2,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '11/17/2025',
    data_inicial: '11/1/2025',
    data_final: '11/30/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'DEZ-',
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 23,
    prestacao: 3,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '12/15/2025',
    data_inicial: '12/1/2025',
    data_final: '12/31/2025',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'JAN-',
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 23,
    prestacao: 4,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '1/15/2026',
    data_inicial: '1/1/2026',
    data_final: '1/31/2026',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'FEV-',
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 23,
    prestacao: 5,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '2/16/2026',
    data_inicial: '2/1/2026',
    data_final: '2/28/2026',
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'MAR-',
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 23,
    prestacao: 6,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '3/16/2026',
    data_inicial: '3/1/2026',
    data_final: '3/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 1,
  },
  {
    designacao: 'ABR-',
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 23,
    prestacao: 7,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '4/15/2026',
    data_inicial: '4/1/2026',
    data_final: '4/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'MAI-',
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 23,
    prestacao: 8,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '5/15/2026',
    data_inicial: '5/1/2026',
    data_final: '5/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'JUN-',
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 23,
    prestacao: 9,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '6/15/2026',
    data_inicial: '6/1/2026',
    data_final: '6/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'JUL-',
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 23,
    prestacao: 10,
    activo: 1,
    activo_posgraduacao: 0,
    data_limite: '7/15/2026',
    data_inicial: '7/1/2026',
    data_final: '7/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'AGO-',
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 23,
    prestacao: 11,
    activo: 0,
    activo_posgraduacao: 0,
    data_limite: '8/17/2026',
    data_inicial: '8/1/2026',
    data_final: '8/31/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
  {
    designacao: 'SET-',
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 23,
    prestacao: 12,
    activo: 0,
    activo_posgraduacao: 0,
    data_limite: '9/15/2026',
    data_inicial: '9/1/2026',
    data_final: '9/30/2026',
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,
  },
];

const mesTempConfigDoutoramento: MESTEMP[] = [
  {
    designacao: "I",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 20,
    prestacao: 1,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "II",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 20,
    prestacao: 2,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "III",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 20,
    prestacao: 3,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "IV",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 20,
    prestacao: 4,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "V",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 20,
    prestacao: 5,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "VI",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 20,
    prestacao: 6,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "VII",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 20,
    prestacao: 7,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "VIII",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 20,
    prestacao: 8,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "IX",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 20,
    prestacao: 9,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "X",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 20,
    prestacao: 10,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XI",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 20,
    prestacao: 11,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XII",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 20,
    prestacao: 12,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XIII",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 20,
    prestacao: 13,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XIV",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 20,
    prestacao: 14,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XV",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 20,
    prestacao: 15,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVI",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 20,
    prestacao: 16,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVII",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 20,
    prestacao: 17,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVIII",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 20,
    prestacao: 18,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XIX",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 20,
    prestacao: 19,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XX",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 20,
    prestacao: 20,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXI",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 20,
    prestacao: 21,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXII",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 20,
    prestacao: 22,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXIII",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 20,
    prestacao: 23,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXIV",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 20,
    prestacao: 24,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXV",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 20,
    prestacao: 25,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXVI",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 20,
    prestacao: 26,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXVII",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 20,
    prestacao: 27,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXVIII",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 20,
    prestacao: 28,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXIX",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 20,
    prestacao: 29,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXX",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 20,
    prestacao: 30,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXXI",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 20,
    prestacao: 31,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXII",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 20,
    prestacao: 32,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXIII",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 20,
    prestacao: 33,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXIV",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 20,
    prestacao: 34,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXV",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 20,
    prestacao: 35,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXVI",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 20,
    prestacao: 36,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXXVII",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 20,
    prestacao: 37,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXXVIII",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 20,
    prestacao: 38,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XXXIX",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 20,
    prestacao: 39,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XL",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 20,
    prestacao: 40,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XLI",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 20,
    prestacao: 41,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XLII",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 20,
    prestacao: 42,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XLIII",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 20,
    prestacao: 43,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XLIV",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 20,
    prestacao: 44,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XLV",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 20,
    prestacao: 45,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XLVI",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 20,
    prestacao: 46,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XLVII",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 20,
    prestacao: 47,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XLVIII",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 20,
    prestacao: 48,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  }
]

const mesTempConfigMestrado: MESTEMP[] = [
  {
    designacao: "I",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 19,
    prestacao: 1,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,
  },
  {
    designacao: "II",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 19,
    prestacao: 2,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },

  {
    designacao: "III",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 19,
    prestacao: 3,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "IV",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 19,
    prestacao: 4,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "V",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 19,
    prestacao: 5,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "VI",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 19,
    prestacao: 6,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "VII",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 19,
    prestacao: 7,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },

  {
    designacao: "VIII",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 19,
    prestacao: 8,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },

  {
    designacao: "IX",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 19,
    prestacao: 9,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },

  {
    designacao: "X",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 19,
    prestacao: 10,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },

  {
    designacao: "XI",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 19,
    prestacao: 11,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },

  {
    designacao: "XII",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 19,
    prestacao: 12,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XIII",
    isencao: 0,
    ordem_mes: 1,
    ano_lectivo: 19,
    prestacao: 13,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },

  {
    designacao: "XIV",
    isencao: 0,
    ordem_mes: 2,
    ano_lectivo: 19,
    prestacao: 14,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XV",
    isencao: 0,
    ordem_mes: 3,
    ano_lectivo: 19,
    prestacao: 15,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVI",
    isencao: 0,
    ordem_mes: 4,
    ano_lectivo: 19,
    prestacao: 16,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVII",
    isencao: 0,
    ordem_mes: 5,
    ano_lectivo: 19,
    prestacao: 17,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XVIII",
    isencao: 0,
    ordem_mes: 6,
    ano_lectivo: 19,
    prestacao: 18,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 1,
    semestre_posgraduacao: 1,

  },
  {
    designacao: "XIX",
    isencao: 0,
    ordem_mes: 7,
    ano_lectivo: 19,
    prestacao: 19,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XX",
    isencao: 0,
    ordem_mes: 8,
    ano_lectivo: 19,
    prestacao: 20,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXI",
    isencao: 0,
    ordem_mes: 9,
    ano_lectivo: 19,
    prestacao: 21,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXII",
    isencao: 0,
    ordem_mes: 10,
    ano_lectivo: 19,
    prestacao: 22,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXIII",
    isencao: 0,
    ordem_mes: 11,
    ano_lectivo: 19,
    prestacao: 23,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  },
  {
    designacao: "XXIV",
    isencao: 0,
    ordem_mes: 12,
    ano_lectivo: 19,
    prestacao: 24,
    activo: 0,
    activo_posgraduacao: 1,
    data_limite: null,
    data_inicial: null,
    data_final: null,
    data_final_desconto: null,
    semestre: 2,
    semestre_posgraduacao: 2,

  }
]

export { mesTempConfig, mesTempConfigDoutoramento, mesTempConfigMestrado };


