export enum TipoCalendario {
  RECURSO = 'RECURSO',
  EXAME_ESPECIAL = 'EXAME_ESPECIAL',
  MELHORIA_NOTAS = 'MELHORIA_NOTAS',
  REINGRESSO = 'REINGRESSO',
  SUBSTITUICAO_UC = 'SUBSTITUICAO_UC',
  MUDANCA_CURSO_INTERNA = 'MUDANCA_CURSO_INTERNA',
  CADEIRAS_EXTRACURRICULARES = 'CADEIRAS_EXTRACURRICULARES',
  MATRICULAS = 'MATRICULAS',
}

export const TIPO_CALENDARIO_CODIGO = {
  [TipoCalendario.RECURSO]: 9,
  [TipoCalendario.EXAME_ESPECIAL]: 10,
  [TipoCalendario.MELHORIA_NOTAS]: 11,
  [TipoCalendario.REINGRESSO]: 12,
  [TipoCalendario.SUBSTITUICAO_UC]: 13,
  [TipoCalendario.MUDANCA_CURSO_INTERNA]: 14,
  [TipoCalendario.CADEIRAS_EXTRACURRICULARES]: 15,
  [TipoCalendario.MATRICULAS]: 16,
} as const;

export type CodigoTipoCalendario =
  (typeof TIPO_CALENDARIO_CODIGO)[TipoCalendario];
